# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog.pedrotp.io
signature: "Hey, I'm Pedro"
email: hi@pedrotp.io
description: > # this means to ignore newlines until "baseurl:"
  This is Pedro Torres-Picón's technical blog. As Pedro gets more technical, so will the posts. For now, <code>expect(this).to.equal(n00b)</code>.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://pedrotp.io" # the base hostname & protocol for your site
twitter_username: pedrotp
github_username:  pedrotp

# Build settings
markdown: kramdown
